<div class="min-h-screen bg-cover bg-center bg-violet-200 rounded-lg overflow-hidden">
    <header class="bg-rose-900 w-full h-10 p-2 flex flex-row justify-between">
        <h1 class="text-xl font-bold text-white text-left w-[60%]">Task Manager</h1>
    </header>
    
    <main class="g-5 flex flex-row justify-center">


        <div id="pending-column" class="flex flex-col w-[30%] bg-violet-100 m-4 p-4 rounded-lg min-h-[150px] gap-2">
            <h3 class="mb-3 font-bold text-gray-900 text-left"><?php echo htmlspecialchars($this->taskTitle)?>:</h3>
            <?php 
            $tasksFind = $this->tasks; ?>
            <?php if (isset($tasksFind) && count($tasksFind) > 0): ?>
                <?php foreach ($tasksFind as $task): ?>
                    <div class="task-item bg-white p-2 rounded shadow-md mb-2 cursor-pointer" data-id="<?php echo $task['id']; ?>" onclick="window.location.href='<?php echo $this->baseUrl(); ?>/task/show?id=<?php echo $task['id']; ?>'">
                        <h4 class="font-medium text-gray-600"><?php echo htmlspecialchars($task['title']); ?></h4>
                        <p class="text-xs text-gray-500"><?php echo $task['user_name']; ?></p>
                    </div>  
                <?php endforeach; ?>
            <?php else: ?>
                <p class="text-gray-600 text-sm font-bold">No se ha encontrado ninguna tarea con este nombre</p>
            <?php endif; ?>

    </main>
    <div class="bg-rose-900 w-[10%] rounded-lg m-4 overflow-hidden flex items-center justify-center mt-10 hover:bg-blue-600">
            <a href="<?php echo $this->baseUrl(); ?>/tasks" class="text-white m-2 text-xs" ><-Home</a>
    </div>

</div>