<div class="min-h-screen bg-cover bg-center bg-violet-200 rounded-lg overflow-hidden">
    <header class="bg-rose-900 w-full h-10 p-2 flex flex-row justify-between">
        <h1 class="text-xl font-bold text-white text-left w-[60%]">Task Manager</h1>
    </header>
    
    <main class="g-5 flex flex-row justify-center">


        <div id="pending-column" class="flex flex-col w-[30%] bg-violet-100 m-4 p-4 rounded-lg min-h-[150px] gap-2">
            <h3 class="mb-3 font-bold text-gray-900 text-left">Pending</h3>
            <?php 
            $pendingTasks = $this->pendingTasks; ?>
            <?php if (isset($pendingTasks) && count($pendingTasks) > 0): ?>
                <?php foreach ($pendingTasks as $task): ?>
                    <div class="task-item bg-white p-2 rounded shadow-md mb-2" >
                        <h4 class="font-medium text-gray-600"><?php echo $task['title']; ?></h4>
                        <p class="text-xs text-gray-500"><?php echo $task['user_name']; ?></p>
                        
                    </div>  
                <?php endforeach; ?>
            <?php else: ?>
                <p class="text-gray-600 text-sm font-bold">No hay tareas pendientes</p>
            <?php endif; ?>
        </div>


        <div class="flex flex-col w-[30%] bg-violet-100 m-4 p-4 rounded-lg min-h-[150px]">
            <h3 class="mb-3 font-bold text-gray-900 text-left">In progress</h3>
            <?php 
                $inProgressTasks = $this->inProgressTasks; ?>
            <?php if (isset($inProgressTasks) && count($inProgressTasks) > 0): ?>
                <?php foreach ($inProgressTasks as $task): ?>
                    <div class="task-item bg-white p-2 rounded shadow-md mb-2" >
                        <h4 class="font-medium text-gray-600"><?php echo $task['title']; ?></h4>
                        <p class="text-xs text-gray-500"><?php echo $task['user_name']; ?></p>
                        
                    </div>   
                <?php endforeach; ?>
            <?php else: ?>
                <p class="text-gray-600 text-sm font-bold">No hay tareas en progreso de momento</p>
            <?php endif; ?>
        </div>


    
        <div class="flex flex-col w-[30%] bg-violet-100 m-4 p-4 rounded-lg min-h-[150px]">
            <h3 class="mb-3 font-bold text-gray-900 text-left">Done</h3>
            <?php 
                $doneTasks = $this->doneTasks; ?>
            <?php if (isset($doneTasks) && count($doneTasks) > 0): ?>
                <?php foreach ($doneTasks as $task): ?>
                    <div class="task-item bg-white p-2 rounded shadow-md mb-2" >
                        <h4 class="font-medium text-gray-600"><?php echo $task['title']; ?></h4>
                        <p class="text-xs text-gray-500"><?php echo $task['user_name']; ?></p>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <p class="text-gray-600 text-sm font-bold">No hay tareas terminadas que mostrar</p>
            <?php endif; ?>
        </div>


    </main>
    <div class="bg-rose-900 w-[10%] rounded-lg m-4 overflow-hidden flex items-center justify-center mt-10 hover:bg-blue-600">
            <a href="<?php echo $this->baseUrl(); ?>/logout" class="text-white m-2 text-xs" >LOGOUT</a>
    </div>

</div>