<div class="flex items-center justify-center min-h-screen bg-cover bg-center px-8">

<div class="flex bg-violet-200 w-[90%] h-[70vh] rounded-xl overflow-hidden">

    <div class="hidden md:flex w-3/5 bg-rose-950 flex-col items-center justify-center text-white ">
        
        <h2 class="text-2xl font-bold">Welcome Page</h2>
        <p class="text-center mt-2">Gestiona tus tareas de manera eficiente</p>
    </div>


    <div class="w-full md:w-2/5 p-6 flex flex-col items-center" >

        <h2 class="text-2xl text-rose-950 font-bold text-center mb-4">Iniciar Sesión</h2>
        <?php $error = $this->error;
            if (isset($error)): ?>
                
                <div class="w-[90%] bg-red-100 border border-red-400 text-red-700 px-4 rounded relative mt4">
                    <?php echo $this->error; ?>
                </div>
            <?php endif; ?>
        <form action="<?php echo $this->baseUrl(); ?>/login" method="post" class="mt-6">
            <div class="mb-4">
                <label class=" text-gray-700">Email Usuario</label>
                <input type="text" required name="email" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
            </div>
            <div class="mb-4">
                <label class="text-gray-700">Contraseña</label>
                <input type="password" required name="password" class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
            </div>
            <button type="submit" class="w-full bg-rose-900 text-white py-2 rounded-lg hover:bg-blue-600">Iniciar sesión</button>
        </form>
            <a href="#" class="text-rose-900 text-sm hover:underline text-center mt-4">¿Has olvidado tu contraseña?</a>
            <a href="<?php echo $this->baseUrl(); ?>/register" class="text-rose-900 text-sm hover:underline text-center mt-4">Crea una nueva cuenta</a>

    </div>   
</div>
</div>