<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Registro</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="../../../web/assets/styles.css">
</head>
<body>

    <div class="flex items-center justify-center min-h-screen bg-cover bg-center p-8">
        <div class="flex bg-violet-200 w-[90%] h-[90vh] rounded-xl p-4 flex flex-col md:w-[50%]">
            <h2 class="text-2xl text-rose-950 font-bold text-center">Crea una cuenta</h2>
            <p class="text-center mt-2">Regístrate para gestionar tus tareas facilmente</p>
            <form action="<?php echo $this->baseUrl(); ?>/register" method="POST" class="mt-6 justify-center flex flex-wrap gap-3">

            
            <?php $error = $this->error;
            if (isset($error)): ?>
                
                <div class="w-[90%] bg-red-100 border border-red-400 text-red-700 px-4 rounded relative mb-4">
                    <?php echo $this->error; ?>
                </div>
            <?php endif; ?>
                <div class="mb-4 w-[90%]">
                    <label class=" text-gray-700">Nombre y Apellido</label>
                    <input type="text" name="user_name" required class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
                </div>
                <div class="mb-4 w-[90%]">
                    <label class="text-gray-700">Email</label>
                    <input type="text" name="email" required class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
                </div>
                <div class="mb-4 w-[90%]">
                    <label class="text-gray-700">Contraseña</label>
                    <input type="password" name="password" required class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
                </div>
                <div class="mb-4 w-[90%] ">
                    <label class="text-gray-700">Confirmar contraseña</label>
                    <input type="password" name="confirm_password" required class="w-full px-4 py-2 border rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500">
                </div>
                <button type="submit" class=" w-[30%] bg-rose-900 text-white py-2 rounded-lg hover:bg-blue-600">Submit</button>
            </form>
                <a href="<?php echo $this->baseUrl(); ?>/login" class="text-rose-900 text-sm hover:underline text-center m-2">¿Ya tienes una cuenta?</a>

        </div>
    </div>
</body>
</html>