<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TO-DO App</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <link rel="stylesheet" href="<?php echo $this->baseUrl(); ?>/assets/styles.css">
</head>

<body class="flex flex-col items-center justify-center min-h-screen bg-img bg-center px-8 p-8">
    <div class="container">
        
        <main class="g-5 flex flex-col justify-center">
            <?php echo $this->content(); ?>
        </main>
        
        <footer>
            <p>&copy; <?php echo date('Y'); ?> - TO-DO App</p>
        </footer>
    </div>
    
</body>
</html>